# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Expense' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Expense
	pod 'SWRevealViewController'
	pod "SwiftChart"
	pod 'SwiftCharts', '~> 0.2'

  target 'ExpenseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExpenseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
